/**
 * @author Kate
 */

window.values = {
    'technique' : [
        'Acrylique',
        'Aquarelle',
        'Sculpture',
        'Calligraphie',
        'Peinture céramique',
        'Collage',
        'Crayon, Mine de',
        'charbon, Graphite',
        'Encre/Stylo',
        'Fusain',
        'Gouache',
        'Huile',
        'Tablette/peinture',
        'Numérique',
        'Photo',
        'Pastel',
        'Pochoir',
        'Vitraux',
        'Peinture aux couteaux'
    ],
    'style' : [
        'Abstrait',
        'Cubisme',
        'Pointillisme',
        'Fauvisme',
        'Figuratif',
        'Hyperréalisme',
        'Nature morte',
        'Peinture Naïve',
        'Pop Art',
        'Réalisme',
        'Manga/BD'
    ],
    'support' : [
        'Papier',
        'Carton',
        'Bois',
        'Verre',
        'Toile',
        'Tissu'
    ],
    'theme' : [
        'Adolescence',
        'Alimentation et gastronomie',
        'Alpinisme',
        'Anarchism',
        'Archeologie',
        'Aviation',
        'Artiste',
        'Dance',
        'Disney',
        'Autisme',
        'Chateau',
        'Chanteur',
        'Train/Chemin de fer',
        'Ecologie',
        'Economie',
        'Féminité',
        'Masculinité',
        'Folie',
        'Guerre',
        'Labyrinthe',
        'Espace',
        'Magie',
        'Ciel',
        'Monde perdu',
        'Consumérisme',
        'Jardin',
        'Maison',
        'la vie',
        'la Mort',
        'Animal imaginaire',
        'TV',
        'Véhicule',
        'La paresse',
        'La gourmandise',
        'L’envie',
        'L’avarice',
        'La Colère',
        'L’orgueil',
        'La luxure',
        'Chasse/pêche',
        'Insecte',
        'Animal',
        'Pays',
        'Fleurs',
        'Nature',
        'Eté',
        'Automne',
        'Hivers',
        'Printemps',
        'Religion',
        'Romance',
        'Sport',
        'Vêtements',
        'Pirate',
        'Vikings',
        'Renaissance',
        'La préhistoire',
        'Antiquité',
        'Moyen Age',
        'Musique',
        'univers fantastique',
        'Oeuvre détournée',
        'Portrait',
        '70’s',
        'Halloween',
        '80’s',
        '90’s',
        'Plage',
        'Montagne',
        'Cirque',
    ]
}
